image:
  repository: <private-registry>/trino  # Air-gapped registry
  tag: "404"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: <your-pull-secret>  # If using private registry

common:
  storageClass: directpv  # Use DirectPV storage class

coordinator:
  resources:
    requests:
      memory: 4Gi
      cpu: 1
  persistentVolume:
    size: 10Gi  # Adjust as needed

worker:
  replicas: 3  # Number of workers
  resources:
    requests:
      memory: 4Gi
      cpu: 1
  persistentVolume:
    size: 10Gi

securityContext:
  runAsUser: 1000
  fsGroup: 1000

config:
  config.properties:
    query.max-memory: 8GB
    query.max-memory-per-node: 2GB
  jvm:
    - "-Xmx3G"
