# values-trino-persistent.yaml (with persistent storage)
image:
  repository: <private repo>/trino
  tag: "474"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: <your-registry-secret>

# Entrypoint configuration for Trino 474
coordinator:
  command: ["/usr/lib/trino/bin/run-trino"]
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
worker:
  command: ["/usr/lib/trino/bin/run-trino"]
  securityContext:
    runAsUser: 1001
    fsGroup: 1001

# Storage configuration
common:
  storageClass: px-csi-replicated
  accessModes: ReadWriteOnce

coordinator:
  persistentVolume:
    enabled: true
    size: 50Gi
    mountPath: /usr/lib/trino/data
worker:
  persistentVolume:
    enabled: true
    size: 100Gi
    mountPath: /usr/lib/trino/data
  replicas: 2

# Resource allocations
resources:
  coordinator:
    requests:
      memory: "8Gi"
      cpu: 2
    limits:
      memory: "8Gi"
      cpu: 2
  worker:
    requests:
      memory: "15Gi"
      cpu: 3
    limits:
      memory: "15Gi"
      cpu: 3

# Configuration
config:
  path: /usr/lib/trino/etc
  configProperties:
    jmx.export: true
    jmx.rmiregistry.port: 9080
    jmx.rmiserver.port: 9081
    jmx.rmiregistry.ssl: false
    jmx.rmiserver.ssl: false
    jmx.rmiregistry.authenticate: false
    jmx.rmiserver.authenticate: false
    http-server.process-forwarded: true
    http-server.authentication.type: PASSWORD,OAUTH2
    http-server.authentication.allow-insecure-over-http: true
    internal-communication.https.required: false

  jvm:
    - "-server"
    - "-Xmx6G"  # For coordinator (8Gi total)
    - "-Xmx12G" # For workers (15Gi total)
    - "-XX:-UseBiasedLocking"
    - "-XX:+UseG1GC"
    - "-Djava.security.krb5.conf=/etc/krb5.conf"
    - "-Djavax.net.ssl.trustStore=/etc/trino/axpcerts/cacerts"
    - "-Djavax.net.ssl.trustStorePassword=changeit"
    - "-Dcom.sun.management.jmxremote.rmi.port=9081"

# Authentication configuration
additionalConfigProperties:
  password-authenticator.name: ldap
  ldap.url: "ldaps://someldap:636"
  ldap.user-bind-pattern: "{USER}@somefqdn.com"
  ldap.ssl.truststore.path: "/etc/trino/axpcerts/someldapcerts.pem"
  # Add other LDAP parameters as needed

# Group provider
groupProvider:
  name: ldap
  ldap.ssl: true
  ldap.user: "someldapuser"
  ldap.url: "ldaps://someldap:636"
  ldap.password: ""
  ldap.search-base: "someusersearchbase"
  ldap.group.search-filter: "(&(objectClass=group))"
  ldap.group.member-attribute: "member"
  ldap.group.name-attribute: "cn"
  ldap.user.member-of-attribute: "memberOf"
  ldap.user.search-filter: "(&(objectClass=user)(sAMAccountName={0}))"

# Volumes for certificates
extraVolumes:
  - name: axpcerts
    secret:
      secretName: starburst-custom-certs
  - name: axpsecurity
    secret:
      secretName: starburst-custom-security

extraVolumeMounts:
  - name: axpcerts
    mountPath: /etc/trino/axpcerts
  - name: axpsecurity
    mountPath: /etc/trino/axpsecurity
    # Uncomment for krb5.conf if needed
    # - name: axpsecurity
    #   mountPath: /etc/krb5.conf
    #   subPath: krb5.conf

# Service exposure
service:
  type: NodePort
  ports:
    http:
      port: 8080
      nodePort: 30080
    # https:
    #   port: 8443
    #   nodePort: 30070

# Catalogs
catalogs:
  hive: |
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore:9083
  # Add other catalogs as needed
