# trino-values.yaml
image:
  repository: <private-registry>/trino
  tag: "474"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: <your-registry-secret>

# RKE2-specific fix for entrypoint
coordinator:
  command: ["/bin/sh", "-c"]
  args: ["exec /usr/lib/trino/bin/run-trino"]
  securityContext:
    runAsUser: 1001  # Important for RKE2 permission handling
    fsGroup: 1001
  volumeMounts:
    - name: config
      mountPath: /usr/lib/trino/etc  # Must match new image structure
      readOnly: true

worker:
  command: ["/bin/sh", "-c"]
  args: ["exec /usr/lib/trino/bin/run-trino"]
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
  volumeMounts:
    - name: config
      mountPath: /usr/lib/trino/etc
      readOnly: true

# Path configuration
common:
  storageClass: directpv
config:
  path: /usr/lib/trino/etc  # Critical path update

# Volume configuration
volumes:
  - name: config
    configMap:
      name: trino-config

# Resource adjustments (example)
coordinator:
  resources:
    requests:
      memory: 4Gi
      cpu: 1
  persistentVolume:
    size: 10Gi

worker:
  replicas: 3
  resources:
    requests:
      memory: 4Gi
      cpu: 1
  persistentVolume:
    size: 10Gi
##########explicitly variable command ####


# trino-values.yaml
coordinator:
  # Force command visibility
  command: ["/bin/sh", "-c"]
  args: 
    - >
      echo "Starting Trino Coordinator";
      ls -l /usr/lib/trino/bin;
      [ -f /usr/lib/trino/bin/run-trino ] && 
        echo "Entrypoint found" && 
        /usr/lib/trino/bin/run-trino ||
        echo "Entrypoint missing";
      sleep 3600

worker:
  # Disable workers temporarily
  replicas: 0

# Keep your existing image and storage config
image:
  repository: <private-registry>/trino
  tag: "474"
common:
  storageClass: directpv
  
