starburstPlatformLicense: somelicense

environment: someenv
sharedSecret: somesharedsecretkey

image:
  pullPolicy: IfNotPresent
  repository: <private repo>
  tag: 443-e.7
initImage:
  pullPolicy: IfNotPresent
  repository: <private repo>
  tag: 1.5.14

configProperties:
  jmx.export: true
  jmx.rmiregistry.port: 9080
  jmx.rmiserver.port: 9081
  jmx.rmiregistry.ssl: false
  jmx.rmiserver.ssl: false
  jmx.rmiregistry.authenticate: false
  jmx.rmiserver.authenticate: false

coordinator:

  resources:
    memory: "8Gi"
    cpu: 2

  etcFiles:
    properties:
      cache.properties: |
        service-database.user=someserviceaccount
        service-database.password=somepassword
        service-database.jdbc-url=jdbc:postgresql://somepostgresqldb:5432/cache_e1
        starburst.user=caching_service
        starburst.password=
        starburst.jdbc-url=jdbc:trino://coordinator:8080
        #starburst.jdbc-url=jdbc:trino://coordinator:8443?SSL=true&SSLVerification=NONE

      log.properties: |
        io.trino=INFO
        #io.trino.server.security.oauth2=DEBUG
        #io.trino.server.ui.OAuth2WebUiAuthenticationFilter=DEBUG
        com.starburstdata.presto=INFO
      password-authenticator-svc.properties: |
        password-authenticator.name=ldap
        ldap.url=ldaps://someldap:636
        ldap.user-bind-pattern=${USER}@somefqdn.com
        ldap.ssl.truststore.path=/etc/starburst/someldapcerts.pem
        ldap.bind-dn=
        ldap.bind-password=
        ldap.group-auth-pattern=
        ldap.user-base-dn=

      password-authenticator-usr.properties: |
        password-authenticator.name=ldap
        ldap.url=ldaps://someldap:636
        ldap.user-bind-pattern=${USER}@somefqdn.com
        ldap.ssl.truststore.path=/etc/starburst/someldapcerts.pem
        ldap.bind-dn=
        ldap.bind-password=
        ldap.group-auth-pattern=
        ldap.user-base-dn=
      group-provider.properties: |
        group-provider.name=ldap
        ldap.ssl=true
        ldap.user=someldapuser
        ldap.url=ldaps://someldap:636
        ldap.password=


        ldap.search-base=someusersearchbase
        ldap.group.search-filter=(&(objectClass=group))
        ldap.group.member-attribute=member
        ldap.group.name-attribute=cn
        ldap.user.member-of-attribute=memberOf
        ldap.user.search-filter=(&(objectClass=user)(sAMAccountName={0}))



  additionalProperties: |
    # Use the following line to enable Insights
    insights.persistence-enabled=true
    insights.metrics-persistence-enabled=true
    insights.jdbc.url=jdbc:postgresql://somepostgreql:5432/insights_e1
    insights.jdbc.user=somesvcid
    insights.jdbc.password=somepswd
    password-authenticator.config-files=/etc/starburst/password-authenticator-usr.properties,/etc/starburst/password-authenticator-svc.properties

    # Internal Communication Configurations
    http-server.process-forwarded=true
    # http-server.authentication.type=PASSWORD
    http-server.authentication.type=PASSWORD,OAUTH2
    http-server.authentication.allow-insecure-over-http=true
    internal-communication.https.required=false


# ------------------------------------------------------------------------------
# Workers
# ------------------------------------------------------------------------------

worker:
  replicas: 2
  deploymentTerminationGracePeriodSeconds: 5 # default is 300; it is actually how long the graceful shutdown waits after it receives the SIGTERM
  starburstWorkerShutdownGracePeriodSeconds: 5 # default is 120
  resources:
    memory: "15Gi"
    cpu: 3


additionalVolumes:
  - path: /etc/starburst/axpcerts
    volume:
      secret:
       secretName: starburst-custom-certs

  - path: /etc/starburst/axpsecurity
    volume:
      secret:
       secretName: starburst-custom-security

  # - path: /etc/krb5.conf
  #   volume:
  #     secret:
  #      secretName: starburst-custom-security
  #   subPath: krb5.conf

expose:
  type: "nodePort"
  nodePort:
    name: "starburst"
    ports:
      http:
        port: 8080
        nodePort: 30080
      https:
        port: 8443
        nodePort: 30070


initFile: |
  #!/bin/bash
  echo "-Dsun.security.krb5.debug=true" >>/etc/starburst/jvm.config
  echo "-Dtrino.client.debugKerberos=true" >>/etc/starburst/jvm.config
  echo "-Djava.security.debug=gssloginconfig,configfile,configparser,logincontext" >>/etc/starburst/jvm.config
  echo "-Djava.security.krb5.conf=/etc/krb5.conf" >>/etc/starburst/jvm.config
  echo "-Djavax.net.ssl.trustStore=/etc/starburst/axpcerts/cacerts" >> /etc/starburst/jvm.config
  echo "-Djavax.net.ssl.trustStorePassword=changeit" >> /etc/starburst/jvm.config
  echo "-Dcom.sun.management.jmxremote.rmi.port=9081" >> /etc/starburst/jvm.config
  exec /usr/lib/starburst/bin/run-starburst
