# trino-values.yaml
image:
  repository: <private-registry>/trino
  tag: "474"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: <your-registry-secret>

# RKE2-specific fix for entrypoint
coordinator:
  command: ["/bin/sh", "-c"]
  args: ["exec /usr/lib/trino/bin/run-trino"]
  securityContext:
    runAsUser: 1001  # Important for RKE2 permission handling
    fsGroup: 1001
  volumeMounts:
    - name: config
      mountPath: /usr/lib/trino/etc  # Must match new image structure
      readOnly: true

worker:
  command: ["/bin/sh", "-c"]
  args: ["exec /usr/lib/trino/bin/run-trino"]
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
  volumeMounts:
    - name: config
      mountPath: /usr/lib/trino/etc
      readOnly: true

# Path configuration
common:
  storageClass: directpv
config:
  path: /usr/lib/trino/etc  # Critical path update

# Volume configuration
volumes:
  - name: config
    configMap:
      name: trino-config

# Resource adjustments (example)
coordinator:
  resources:
    requests:
      memory: 4Gi
      cpu: 1
  persistentVolume:
    size: 10Gi

worker:
  replicas: 3
  resources:
    requests:
      memory: 4Gi
      cpu: 1
  persistentVolume:
    size: 10Gi
